query {
  transactions(
    tags: [
      { name: "App-Name", values: ["ArVerify"] }
      { name: "Type", values: ["Genesis"] }
    ]
  ) {
    edges {
      node {
        owner {
          address
        }
      }
    }
  }
}
