query($owner: String!, $recipient: String!) {
  transactions(
    owners: [$owner]
    recipients: [$recipient]
    tags: [
      { name: "App-Name", values: ["ArVerify"] }
      { name: "Type", values: ["FEE_NODE"] }
    ]
    first: 1
  ) {
    edges {
      node {
        quantity {
          winston
        }
      }
    }
  }
}
