query($nodes: [String!], $addr: String!) {
  transactions(
    owners: $nodes
    tags: [
      { name: "Application", values: ["ArVerify"] }
      { name: "Action", values: ["Verification"] }
      { name: "Method", values: ["Google"] }
      { name: "Address", values: [$addr] }
    ]
  ) {
    edges {
      node {
        id
        tags {
          name
          value
        }
      }
    }
  }
}
