query($nodes: [String!], $addr: String!) {
  transactions(
    owners: $nodes
    tags: [
      { name: "App-Name", values: ["ArVerify"] }
      { name: "Type", values: ["Verification"] }
      { name: "Address", values: [$addr] }
    ]
  ) {
    edges {
      node {
        id
        tags {
          name
          value
        }
      }
    }
  }
}
